### ISSUE TITLE
if i could prove that i never touched my balls would you promise not to tell another soul what you saw?

### ISSUE THREAD

**Issue by janLuna** [NoNameGivenCoder/NoNameVerse#2]
i love having gay sex with my gay girlfriend

**Comment by davidsosa2022** [comment]
what the fuck is wrong wih you

**Comment by janLuna** [comment]
nyaaaa :3

**Comment by Landonb0909** [comment]
> what the fuck is wrong wih you

rawr x3

**Comment by janLuna** [comment]
> > what the fuck is wrong wih you
> 
> rawr x3

nuzzles pounces on you uwu you so warm, couldnt help but notice your bulge from across the floor
(https://www.youtube.com/watch?v=h6DNdop6pD8)

**Comment by MattTheTekie** [comment]
@NoNameGivenCoder Get these two issues edited and removed. This is ridiclous.
